import type { Metadata } from "next";

import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "LeiaBotDashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./public/favicon.png" />
        {/* Add your favicon here */}
      </head>
      <body
        className={`${poppins.className} scroll-smooth bg-dark-dark-green antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
